@defaultUrl = http://localhost:3000/courses/

### This route finds all courses
GET {{defaultUrl}}

### This route returns one course by its id
GET {{defaultUrl}}5382241e-4b26-4edd-b73f-4e92af616c43

### This route creates a course
POST {{defaultUrl}}
Content-Type: application/json

{
    "course_name": "Math",
    "description": "Numbers"
}

### This route updates a course by its id
PATCH {{defaultUrl}}593e2c09-4597-4cfa-ba08-729a15296629
Content-Type: application/json

{
    "course_name": "Portuguese",
    "description": "Portuguese course"
}

### This route removes a course by its id:
DELETE {{defaultUrl}}a8cede5b-2fa2-4cb9-995a-6887f6e3f4b9